version: "3.9"

services:
  frontend:
    image: "shadadelic/frontend:dev"
    ports:
      - "8080:8080"
    depends_on:
      - backend
  backend:
    image: "shadadelic/backend:dev"
    ports:
      - "8000:8000"
  database:
    image: 'bitnami/postgresql:14'
    volumes:
      - ./environment/postgresql-persistence:/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_DATABASE=resonance
      - POSTGRESQL_PASSWORD=password123
  adminer:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DEFAULT_DB_NAME: resonance
    ports:
      - 9000:8080
