apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resonance.fullname" . }}
  labels:
    {{- include "resonance.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- .Files.Get "files/config.yaml" | nindent 4 -}}