apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resonance.fullname" . }}
  labels:
    {{- include "resonance.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "resonance.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "resonance.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "resonance.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: migrations
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          args: ['migrate', 'up']
          volumeMounts:
            - name: config-volume
              mountPath: /home/nonroot/config.yaml
              subPath: config.yaml
      containers:
        - name: backend
          args: ["serve"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /home/nonroot/config.yaml
              subPath: config.yaml
          ports:
            - name: backend
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: backend
          readinessProbe:
            httpGet:
              path: /healthz
              port: backend
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: frontend
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: frontend
          readinessProbe:
            httpGet:
              path: /
              port: frontend
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "resonance.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
