apiVersion: v1
kind: Service
metadata:
  name: {{ include "resonance.fullname" . }}
  labels:
    {{- include "resonance.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: targetport
      protocol: TCP
      name: http
  selector:
    {{- include "resonance.selectorLabels" . | nindent 4 }}
